# Generated by Django 2.2.1 on 2019-05-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=15)),
                ('Mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
