# Generated by Django 2.2.1 on 2019-05-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlanta',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('t_max', models.SmallIntegerField()),
                ('t_min', models.SmallIntegerField()),
                ('p_max', models.PositiveSmallIntegerField()),
                ('p_min', models.PositiveSmallIntegerField()),
                ('h_max', models.PositiveIntegerField()),
                ('h_min', models.PositiveIntegerField()),
            ],
        ),
    ]
