# Generated by Django 2.2.1 on 2019-05-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.PositiveSmallIntegerField()),
                ('Pressure', models.PositiveSmallIntegerField()),
                ('Humidity', models.PositiveSmallIntegerField()),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Plant_type', models.CharField(max_length=50)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Usuario')),
            ],
        ),
    ]
