# Generated by Django 2.2.1 on 2019-06-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionPlantas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.SmallIntegerField()),
                ('Pressure', models.PositiveSmallIntegerField()),
                ('Humidity', models.PositiveSmallIntegerField()),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionPlantas.Plantas')),
            ],
        ),
    ]
