# Generated by Django 2.2.1 on 2019-05-28 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('plant_name', models.CharField(max_length=20)),
                ('plant_ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('plant_type', models.CharField(choices=[('Rosa', 'Rosa'), ('Lilium', 'Lilium'), ('Cactus', 'Cactus'), ('Cannabis', 'Cannabis'), ('Arbol generico', 'Arbol generico'), ('Otro', 'Otro')], default='Otro', max_length=1)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Usuario')),
            ],
        ),
    ]
