# Generated by Django 2.2.1 on 2019-06-01 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TiposPlantas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('plant_ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=20)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TiposPlantas.TipoPlanta')),
            ],
        ),
    ]
